# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 800)

        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 700, 700))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 700, 700))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)

        self.tableWidget.setColumnWidth(3, 245)

        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.tableWidget.setSelectionMode(QAbstractItemView.SingleSelection)

        # 设置表格不可编辑

        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 700, 51))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_select = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_select.setGeometry(QtCore.QRect(560, 20, 75, 23))
        self.btn_select.setObjectName("btn_select")
        self.line_ip = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_ip.setGeometry(QtCore.QRect(170, 20, 131, 23))
        self.line_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.line_ip.setObjectName("line_ip")
        self.label_serverinfo = QtWidgets.QLabel(self.groupBox_2)
        self.label_serverinfo.setGeometry(QtCore.QRect(29, 20, 131, 23))
        self.label_serverinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serverinfo.setObjectName("label_serverinfo")
        self.line_filter = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_filter.setGeometry(QtCore.QRect(440, 20, 113, 23))
        self.line_filter.setObjectName("line_filter")
        self.comboBox_filter = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_filter.setGeometry(QtCore.QRect(320, 20, 111, 23))
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.comboBox_filter.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "共享文件管理"))
        MainWindow.setWindowIcon(QIcon("./re.png"))
        self.groupBox.setTitle(_translate("MainWindow", "data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文本ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "访问者"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "打开的文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "info"))
        self.btn_select.setText(_translate("MainWindow", "查 询"))
        self.line_ip.setText(_translate("MainWindow", "192.168.58.133:5985"))
        self.label_serverinfo.setText(_translate("MainWindow", "远程Server地址:"))
        self.comboBox_filter.setItemText(0, _translate("MainWindow", "关键字查询"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
